trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- powershell: docker images

- powershell: ./src/Run.ps1 -Build
  displayName: 'Run dockerfile'

- powershell: ./src/Run.ps1 -PublishTests '$(Common.TestResultsDirectory)'
  condition: succeededOrFailed()
  displayName: 'Copy test files from image'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  displayName: Publish test results
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx' 
    searchFolder: '$(Common.TestResultsDirectory)'
    failTaskOnFailedTests: true