trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- powershell: ./src/The.Initial.Run.ps1 '$(Common.TestResultsDirectory)'
  displayName: 'Run script'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  displayName: Publish test results
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx' 
    searchFolder: '$(Common.TestResultsDirectory)'
    failTaskOnFailedTests: true